sudo: required
dist: trusty
language: generic
script: make
before_deploy:
- openssl aes-256-cbc -K $encrypted_8300972bd4a2_key -iv $encrypted_8300972bd4a2_iv -in signing.key.enc -out signing.key -d
- make deploy
deploy:
  provider: releases
  api_key:
    secure: s5Qq5vxHfeGx8qGh+7Fs7yanlQtJZEOCM+JrEAyaNhJMd5Tvols77CasGvMgbPQSR8IU7HTcMrdyZ/Rx+0+0dHYeRk+hinqYY5ihYmwiHMJDvE4cHnuMZ7enkNVeMJp12fe7CEYBgxv+QtIB7X0TPwUfYoxOeNpaQW+7znZ/QchxseFkQfYe1OlWDziyjfIuBzJMgaAXGehPFqpSS2tezH9qDhfGTkfkAlIpEkSxnc7GnJLiLecTzcDkJbhhOZ2PmDhPdC5UmpfhgnDK0M/VQqVCn42XMTY/9Alfq+MwPFKGK5UUSRYy7MAKPXAg5YbJpvSM/ig90SqrdG/XhJXtvOHWmdO/uvzK6DG2kZL4FLbyo1mhC8u8j9uudwiXRX7T9w5UVbJVy18w3qUqCdGSD7cDDIVZyoWFYKgx6ll2AVOoNgtkdx5fV5AL/QSjBBPsIacnNy2wfe+za/DYGLvDGTrDxBNLTk+WOYIbvTR5ulhDEWzl6xwtaNTma5XLcYf7nowU/OUP0M+UGDs913Peu8yrnQplF51slxMdiuOXQtTfMcm3dUYzYlLE3ynuuwDxFjoQMIFY349Q/+GILWVNFrj5/fCj6fkXLFPVryBi9YSYAI8+AvhRG/k5b7rNmYDq2R0JPBi4ThcwBNgjDDdfNoqEVtUZxfTNw8AmnxmS0yY=
  file:
    - dist/dit4c-imageserver-swift.linux.amd64.aci
    - dist/dit4c-imageserver-swift.linux.amd64.aci.asc
  on:
    tags: true
    repo: dit4c/dit4c-imageserver-swift
  skip_cleanup: true
