[template]
src = "nginx.conf.tmpl"
dest = "/tmp/nginx.conf"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/nameservers",
  "/portal/uri",
  "/tls/cert",
  "/tls/key",
  "/os/token",
  "/swift/container/url",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/nginx -s reload"
